build fat-mach-o binary for pygore
goretk/libgore pull request #9
Opened 2023-02-09 12:19 UTC by 3viLMonk3y

Fixed an issue with [pygore](https://github.com/goretk/pygore) where the [pip pygore package](https://github.com/goretk/pygore/issues/20) comes with amd64 compiled `libgore.dylib` and lacks support for Applie Silicon arm64 architecture.

The Makefile was changed to compile both an amd64 and an arm64 version and create a fat-mach-o universal `libgore.dylib` binary.

Tested to work on my MBP M1 14"

2023-02-14 20:19 UTC, TcM1911 requested changes
Thank you for contributing.

2023-02-14 20:19 UTC, TcM1911 commented on Makefile
> +	@GOARCH=amd64 $(DARWIN_GO_ENV) $(GO) build -o $(APP).amd64.dylib $(BUILD_OPTS) .
Remove `$(ARCH)` from `DARWIN_GO_ENV`

2023-04-09 17:36 UTC, 3viLMonk3y commented on Makefile
> -ARCH=GOARCH=amd64
Missed it, thanks, reintroduced the variable.

2023-04-09 17:36 UTC, 3viLMonk3y commented on Makefile
> +	@GOARCH=amd64 $(DARWIN_GO_ENV) $(GO) build -o $(APP).amd64.dylib $(BUILD_OPTS) .
Deleted $(ARCH).

2023-04-14 10:55 UTC, TcM1911 approved these changes

2023-04-14 10:56 UTC, merged

2023-08-10 19:34 UTC, ApexHack3r commented
@TcM1911 - Hi, just checking by to see if this will be released as a patch version?

Would be cool if PyGoRE would be updated as well so users can enjoy this library on their Apple silicon MBPs with a simple pip install 😁.